onlyBuiltDependencies:
  - 7zip-bin
  - '@ampproject/remapping'
  - '@babel/code-frame'
  - '@babel/compat-data'
  - '@babel/core'
  - '@babel/generator'
  - '@babel/helper-compilation-targets'
  - '@babel/helper-module-imports'
  - '@babel/helper-module-transforms'
  - '@babel/helper-plugin-utils'
  - '@babel/helper-string-parser'
  - '@babel/helper-validator-identifier'
  - '@babel/helper-validator-option'
  - '@babel/helpers'
  - '@babel/parser'
  - '@babel/plugin-transform-arrow-functions'
  - '@babel/template'
  - '@babel/traverse'
  - '@babel/types'
  - '@breadc/color'
  - '@breadc/death'
  - '@ctrl/tinycolor'
  - '@develar/schema-utils'
  - '@electron-toolkit/eslint-config-prettier'
  - '@electron-toolkit/eslint-config-ts'
  - '@electron-toolkit/preload'
  - '@electron-toolkit/tsconfig'
  - '@electron-toolkit/utils'
  - '@electron/asar'
  - '@electron/get'
  - '@electron/node-gyp'
  - '@electron/notarize'
  - '@electron/osx-sign'
  - '@electron/rebuild'
  - '@electron/universal'
  - '@element-plus/icons-vue'
  - '@esbuild/win32-x64'
  - '@eslint-community/eslint-utils'
  - '@eslint-community/regexpp'
  - '@eslint/config-array'
  - '@eslint/config-helpers'
  - '@eslint/core'
  - '@eslint/eslintrc'
  - '@eslint/js'
  - '@eslint/object-schema'
  - '@eslint/plugin-kit'
  - '@floating-ui/core'
  - '@floating-ui/dom'
  - '@floating-ui/utils'
  - '@gar/promisify'
  - '@humanfs/core'
  - '@humanfs/node'
  - '@humanwhocodes/module-importer'
  - '@humanwhocodes/retry'
  - '@img/sharp-win32-x64'
  - '@isaacs/cliui'
  - '@jridgewell/gen-mapping'
  - '@jridgewell/resolve-uri'
  - '@jridgewell/set-array'
  - '@jridgewell/sourcemap-codec'
  - '@jridgewell/trace-mapping'
  - '@malept/cross-spawn-promise'
  - '@malept/flatpak-bundler'
  - '@naria2/node'
  - '@naria2/options'
  - '@naria2/win32-x64'
  - '@nodelib/fs.scandir'
  - '@nodelib/fs.stat'
  - '@nodelib/fs.walk'
  - '@npmcli/fs'
  - '@npmcli/move-file'
  - '@pkgjs/parseargs'
  - '@pkgr/core'
  - '@rollup/rollup-win32-x64-msvc'
  - '@sec-ant/readable-stream'
  - '@sindresorhus/is'
  - '@sindresorhus/merge-streams'
  - '@sqltools/formatter'
  - '@sxzz/popperjs-es'
  - '@szmarczak/http-timer'
  - '@tailwindcss/node'
  - '@tailwindcss/oxide'
  - '@tailwindcss/oxide-win32-x64-msvc'
  - '@tailwindcss/vite'
  - '@tootallnate/once'
  - '@types/cacheable-request'
  - '@types/debug'
  - '@types/estree'
  - '@types/fs-extra'
  - '@types/glob'
  - '@types/http-cache-semantics'
  - '@types/http-proxy'
  - '@types/json-schema'
  - '@types/keyv'
  - '@types/lodash'
  - '@types/lodash-es'
  - '@types/minimatch'
  - '@types/ms'
  - '@types/node'
  - '@types/responselike'
  - '@types/shelljs'
  - '@types/web-bluetooth'
  - '@types/yauzl'
  - '@typescript-eslint/eslint-plugin'
  - '@typescript-eslint/parser'
  - '@typescript-eslint/scope-manager'
  - '@typescript-eslint/type-utils'
  - '@typescript-eslint/types'
  - '@typescript-eslint/typescript-estree'
  - '@typescript-eslint/utils'
  - '@typescript-eslint/visitor-keys'
  - '@vitejs/plugin-vue'
  - '@volar/language-core'
  - '@volar/source-map'
  - '@volar/typescript'
  - '@vue/compiler-core'
  - '@vue/compiler-dom'
  - '@vue/compiler-sfc'
  - '@vue/compiler-ssr'
  - '@vue/compiler-vue2'
  - '@vue/devtools-api'
  - '@vue/language-core'
  - '@vue/reactivity'
  - '@vue/runtime-core'
  - '@vue/runtime-dom'
  - '@vue/server-renderer'
  - '@vue/shared'
  - '@vueuse/core'
  - '@vueuse/metadata'
  - '@vueuse/shared'
  - '@xmldom/xmldom'
  - abbrev
  - acorn
  - acorn-jsx
  - agent-base
  - agentkeepalive
  - aggregate-error
  - ajv
  - ajv-keywords
  - alien-signals
  - ansi-regex
  - ansi-styles
  - ansis
  - app-builder-bin
  - app-builder-lib
  - app-root-path
  - aproba
  - archiver
  - archiver-utils
  - are-we-there-yet
  - argparse
  - async
  - async-exit-hook
  - async-validator
  - asynckit
  - at-least-node
  - axios
  - balanced-match
  - base64-js
  - better-sqlite3
  - bindings
  - bl
  - bluebird
  - bluebird-lst
  - boolbase
  - boolean
  - brace-expansion
  - braces
  - browserslist
  - buffer
  - buffer-crc32
  - buffer-from
  - builder-util
  - builder-util-runtime
  - bundle-name
  - cac
  - cacache
  - cacheable-lookup
  - cacheable-request
  - call-bind-apply-helpers
  - callsites
  - caniuse-lite
  - chalk
  - chokidar
  - chownr
  - chromium-pickle-js
  - ci-info
  - clean-stack
  - cli-cursor
  - cli-spinners
  - cliui
  - clone
  - clone-response
  - color
  - color-convert
  - color-name
  - color-string
  - color-support
  - combined-stream
  - commander
  - compare-version
  - compress-commons
  - concat-map
  - config-file-ts
  - console-control-strings
  - convert-source-map
  - core-util-is
  - crc-32
  - crc32-stream
  - cross-spawn
  - cssesc
  - csstype
  - dayjs
  - de-indent
  - debug
  - decompress-response
  - deep-extend
  - deep-is
  - default-browser
  - default-browser-id
  - defaults
  - defer-to-connect
  - define-data-property
  - define-lazy-prop
  - define-properties
  - delayed-stream
  - delegates
  - depd
  - destroy
  - detect-libc
  - detect-node
  - dir-compare
  - dmg-builder
  - dotenv
  - dotenv-expand
  - dunder-proto
  - eastasianwidth
  - ee-first
  - ejs
  - electron
  - electron-builder
  - electron-builder-squirrel-windows
  - electron-publish
  - electron-to-chromium
  - electron-updater
  - electron-vite
  - element-plus
  - emoji-regex
  - encodeurl
  - encoding
  - end-of-stream
  - enhanced-resolve
  - entities
  - env-paths
  - err-code
  - es-define-property
  - es-errors
  - es-object-atoms
  - es-set-tostringtag
  - es6-error
  - esbuild
  - escalade
  - escape-html
  - escape-string-regexp
  - eslint
  - eslint-config-prettier
  - eslint-plugin-prettier
  - eslint-plugin-vue
  - eslint-scope
  - eslint-visitor-keys
  - espree
  - esquery
  - esrecurse
  - estraverse
  - estree-walker
  - esutils
  - etag
  - eventemitter3
  - execa
  - expand-template
  - exponential-backoff
  - extract-zip
  - fast-deep-equal
  - fast-diff
  - fast-glob
  - fast-json-stable-stringify
  - fast-levenshtein
  - fastq
  - fd-slicer
  - figures
  - file-entry-cache
  - file-uri-to-path
  - filelist
  - fill-range
  - finalhandler
  - find-up
  - flat-cache
  - flatted
  - follow-redirects
  - foreground-child
  - form-data
  - fresh
  - fs-constants
  - fs-extra
  - fs-minipass
  - fs.realpath
  - function-bind
  - gauge
  - gensync
  - get-caller-file
  - get-intrinsic
  - get-port
  - get-proto
  - get-stream
  - github-from-package
  - glob
  - glob-parent
  - global-agent
  - globals
  - globalthis
  - gopd
  - got
  - graceful-fs
  - graphemer
  - has-flag
  - has-property-descriptors
  - has-symbols
  - has-tostringtag
  - has-unicode
  - hasown
  - he
  - hosted-git-info
  - http-cache-semantics
  - http-errors
  - http-proxy
  - http-proxy-agent
  - http-proxy-middleware
  - http2-wrapper
  - https-proxy-agent
  - human-signals
  - humanize-ms
  - iconv-lite
  - ieee754
  - ignore
  - import-fresh
  - imurmurhash
  - indent-string
  - infer-owner
  - inflight
  - inherits
  - ini
  - interpret
  - ip-address
  - is-arrayish
  - is-ci
  - is-core-module
  - is-docker
  - is-extglob
  - is-fullwidth-code-point
  - is-glob
  - is-inside-container
  - is-interactive
  - is-lambda
  - is-number
  - is-plain-obj
  - is-plain-object
  - is-stream
  - is-unicode-supported
  - is-wsl
  - isarray
  - isbinaryfile
  - isexe
  - jackspeak
  - jake
  - jiti
  - js-tokens
  - js-yaml
  - jsbn
  - jsesc
  - json-buffer
  - json-schema-traverse
  - json-stable-stringify-without-jsonify
  - json-stringify-safe
  - json5
  - jsonfile
  - keyv
  - lazy-val
  - lazystream
  - levn
  - lightningcss
  - lightningcss-win32-x64-msvc
  - locate-path
  - lodash
  - lodash-es
  - lodash-unified
  - lodash.defaults
  - lodash.difference
  - lodash.escaperegexp
  - lodash.flatten
  - lodash.isequal
  - lodash.isplainobject
  - lodash.merge
  - lodash.union
  - log-symbols
  - lowercase-keys
  - lru-cache
  - magic-string
  - make-fetch-happen
  - maria2
  - matcher
  - math-intrinsics
  - meilisearch
  - memoize-one
  - merge2
  - micromatch
  - mime
  - mime-db
  - mime-types
  - mimic-fn
  - mimic-response
  - minimatch
  - minimist
  - minipass
  - minipass-collect
  - minipass-fetch
  - minipass-flush
  - minipass-pipeline
  - minipass-sized
  - minizlib
  - mitt
  - mkdirp
  - mkdirp-classic
  - ms
  - muggle-string
  - nanoid
  - napi-build-utils
  - naria2
  - natural-compare
  - negotiator
  - nice-try
  - node-abi
  - node-addon-api
  - node-api-version
  - node-gyp
  - node-releases
  - nopt
  - normalize-path
  - normalize-url
  - normalize-wheel-es
  - npm-run-path
  - npmlog
  - nth-check
  - object-keys
  - on-finished
  - once
  - onetime
  - open
  - optionator
  - ora
  - p-cancelable
  - p-finally
  - p-limit
  - p-locate
  - p-map
  - package-json-from-dist
  - parent-module
  - parse-ms
  - parseurl
  - path-browserify
  - path-exists
  - path-is-absolute
  - path-key
  - path-parse
  - path-scurry
  - pe-library
  - pend
  - picocolors
  - picomatch
  - plist
  - postcss
  - postcss-selector-parser
  - prebuild-install
  - prelude-ls
  - prettier
  - prettier-linter-helpers
  - pretty-ms
  - proc-log
  - process-nextick-args
  - progress
  - promise-inflight
  - promise-retry
  - proxy-from-env
  - pump
  - punycode
  - queue-microtask
  - quick-lru
  - range-parser
  - rc
  - read-binary-file-arch
  - readable-stream
  - readdir-glob
  - readdirp
  - rechoir
  - reflect-metadata
  - require-directory
  - requires-port
  - resedit
  - resolve
  - resolve-alpn
  - resolve-from
  - responselike
  - restore-cursor
  - retry
  - reusify
  - rimraf
  - roarr
  - rollup
  - run-applescript
  - run-parallel
  - safe-buffer
  - safer-buffer
  - sanitize-filename
  - sax
  - semver
  - semver-compare
  - send
  - serialize-error
  - serve-static
  - set-blocking
  - setprototypeof
  - sha.js
  - sharp
  - shebang-command
  - shebang-regex
  - shelljs
  - signal-exit
  - simple-concat
  - simple-get
  - simple-swizzle
  - simple-update-notifier
  - smart-buffer
  - socks
  - socks-proxy-agent
  - source-map
  - source-map-js
  - source-map-support
  - sprintf-js
  - sql-highlight
  - sqlite3
  - ssri
  - stat-mode
  - statuses
  - string-width
  - string_decoder
  - strip-ansi
  - strip-eof
  - strip-final-newline
  - strip-json-comments
  - sumchecker
  - supports-color
  - supports-preserve-symlinks-flag
  - synckit
  - tailwindcss
  - tapable
  - tar
  - tar-fs
  - tar-stream
  - temp-file
  - tiny-typed-emitter
  - tmp
  - tmp-promise
  - to-regex-range
  - toidentifier
  - tree-kill
  - truncate-utf8-bytes
  - ts-api-utils
  - tslib
  - tunnel-agent
  - type-check
  - type-fest
  - typeorm
  - typescript
  - typescript-eslint
  - undici-types
  - unicorn-magic
  - unique-filename
  - unique-slug
  - universalify
  - unpipe
  - update-browserslist-db
  - uri-js
  - utf8-byte-length
  - util-deprecate
  - uuid
  - vite
  - vscode-uri
  - vue
  - vue-demi
  - vue-eslint-parser
  - vue-router
  - vue-tsc
  - wcwidth
  - which
  - wide-align
  - word-wrap
  - wrap-ansi
  - wrappy
  - ws
  - xml-name-validator
  - xmlbuilder
  - y18n
  - yallist
  - yargs
  - yargs-parser
  - yauzl
  - yocto-queue
  - yoctocolors
  - zip-stream
